export const SHOW_NEW_CHARACTER_FORM = 'SHOW_NEW_CHARACTER_FORM';
export const SHOW_GAME_CONTROL = 'SHOW_GAME_CONTROL';
export const SHOW_SPLASH_SCREEN = 'SHOW_SPLASH_SCREEN';
export const ADD_PLAYER_CHARACTER = 'ADD_PLAYER_CHARACTER';
export const DELETE_PLAYER_CHARACTER = 'DELETE_PLAYER_CHARACTER';